### ISSUE TITLE
Lowering VRam

### ISSUE THREAD

**Issue by Night1099** [giuvecchio/matfuse-sd#1]
Hello gluvecchio! Your work looks very exciting and I want train my dataset with it.

The only huddle I see is the inference vram requirement, is there a new feature on the way to help this, or a way to use lower precision, thanks

**Comment by Night1099** [comment]
I just now saw your mat forger project, is there plans to release how to train that type of model or further optimize it?

**Comment by giuvecchio** [comment]
Hi! About vram requirements, you can run the model at half precision and prune unnecessary parts of it.
There's an awesome repository that does it for you: https://github.com/lopho/stable-diffusion-prune
Regarding MatForger, it can be trained with this same codebase just switching the autoencoder architecture to the VAE. You can also finetune it directly in diffusers: https://huggingface.co/docs/diffusers/tutorials/basic_training
