### ISSUE TITLE
Available checkpoint?

### ISSUE THREAD

**Issue by hjwdzh** [giuvecchio/matfuse-sd#2]
Great work. Do you plan to release pretrained model? It would be easier for followers to try the inference:)

**Comment by giuvecchio** [comment]
Hi, thanks for the interest in our work. Yes, we are working to release the checkpoint soon enough!

**Comment by giuvecchio** [comment]
Hi @hjwdzh we are making the checkpoint available through hugging face. You will find the link to the model in the README.
