### ISSUE TITLE
Missing modules for training

### ISSUE THREAD

**Issue by Cold5tar** [giuvecchio/matfuse-sd#3]
While trying to run training I am faced with multiple modules that were not mentioned in the `requirements.txt` file.

Now I was installing them 1 by 1 until one of them is not recognizible. Error `ModuleNotFoundError: No module named 'Pylette.color_extraction'`

Do you have any idea why that might be happening? I cant find any info on this module. Previous to this I installed `Pylette` as it was also blocking the training execution

**Comment by rensortino** [comment]
Hi, I am currently working on this issue, the `requirements.txt` file was not updated and apparently the [Pylette ](https://github.com/qTipTip/Pylette) module slightly changed its importing workflow in the last versions.

**Comment by Cold5tar** [comment]
Thanks for letting me know, impatiently waiting so I can start training :D

**Comment by rensortino** [comment]
We fixed the problem with Pylette and addressed some other minor issues in the codebase. Now you should be able to train on your own data
