### ISSUE TITLE
Training crashes on step 2000

### ISSUE THREAD

**Issue by Night1099** [giuvecchio/matfuse-sd#5]
I get this error when script reaches step 2000 I assume it's a img log error

```
TypeError: VQModelMulti.forward() missing 1 required positional argument: 'return_pred_indices'
```

**Comment by rensortino** [comment]
There was a default value not set in the VQModelMulti class, fixed in https://github.com/giuvecchio/matfuse-sd/commit/59e867de7d59b732f977bc4dac65983366ff3d09

**Comment by Night1099** [comment]
Thanks!
